//! `fm-mcp-config-files-quarantined-bak-files-with-tokens` — P1
//! auto-fix via `Op::Chmod`.
//!
//! **Subsystem**: mcp_config_files.
//!
//! ## What's broken
//!
//! The `am setup` / `am doctor archive-normalize` paths back up
//! MCP client config files with a timestamped suffix before
//! rewriting them. The naming convention (per
//! `mcp_config.rs:487-499`) is
//! `<basename>.<YYYYMMDD>_<HHMMSS>(-NN)?.bak`. These backups
//! often contain stale bearer tokens, and they often inherit
//! the umask of the writer (usually 0o644) — exposing the token
//! to any local user that can read the directory.
//!
//! This FM is DIFFERENT from `world_readable_token_bak`:
//!
//! - `world_readable_token_bak` matches by **suffix** (`.bak`,
//!   `.tmp`, `.orig`, `.old`, `.backup`) and is given an
//!   explicit candidate list by the caller.
//! - **This FM** matches by **regex** specifically for
//!   timestamped backups, walks MCP config dirs directly, and
//!   flags both world/group-readable backups AND tokenless
//!   backups in the project tree (hygiene).
//!
//! ## Detection (pure)
//!
//! 1. Enumerate MCP config directories via
//!    `mcp_config::detect_mcp_config_locations_default()`.
//! 2. For each parent dir of a config location, read one level
//!    of entries.
//! 3. Filter to basenames matching
//!    `^[A-Za-z0-9_.\-]+\.\d{8}_\d{6}(-\d{2})?\.bak$`.
//! 4. For each match, reject symlinks, read first 64 KiB, check
//!    for token-shape content; emit finding if token-shape AND
//!    mode has group/other bits set.
//!
//! ## Fix
//!
//! **Auto-fix (defense-in-depth):** each flagged backup is
//! chmodded to `0o600` via the chokepoint (`Op::Chmod`). The
//! prior mode is recorded in `actions.jsonl`, so
//! `am doctor undo <run-id>` restores byte-identical mode bits.
//! Entries that vanish between detect-time and fix-time count as
//! `actions_skipped`. The file content is NOT moved or modified —
//! the auto-fix only narrows POSIX permissions to owner-only,
//! matching the canonical mode the writer SHOULD have used.
//!
//! The stronger remediation (move into `.doctor/quarantine/mcp-
//! config-bak/`) remains documented for manual application when
//! the operator has rotated the token and wants the backup out of
//! the config dir entirely; that needs the chokepoint's
//! Op::Rename quarantine path plus token-rotation coordination.

#![forbid(unsafe_code)]

use super::{FindingRemediation, FixOutcome};
use crate::doctor::mutate::{MutateContext, MutateError, Op, mutate};
use regex::Regex;
use serde::Serialize;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::OnceLock;

pub const FM_ID: &str = "fm-mcp-config-files-quarantined-bak-files-with-tokens";
const FM_SEVERITY: &str = "P1";
const FM_SUBSYSTEM: &str = "mcp_config_files";

/// Canonical owner-only mode the chokepoint chmods flagged backups
/// to. Matches the canonical mode the writer should have used and
/// the `world_readable_token_bak` FM's `SAFE_MODE`.
pub const SAFE_MODE: u32 = 0o600;

/// Bytes scanned for token-shape content. 64 KiB matches the
/// repair_spec.
const SCAN_PREFIX_BYTES: usize = 65536;

/// Token-shape patterns (case-insensitive). Same family the
/// other secrets-env FMs use for consistency.
const TOKEN_SHAPE_PATTERNS: &[&str] = &[
    "HTTP_BEARER_TOKEN",
    "authorization=",
    "bearer=",
    "token=",
    "secret=",
    "api_key=",
    "\"authorization\"",
    "\"bearer\"",
    "\"token\"",
];

fn backup_filename_regex() -> &'static Regex {
    static RE: OnceLock<Regex> = OnceLock::new();
    RE.get_or_init(|| {
        // ASCII-only digits intentional (pass-35AA review F3,
        // Gemini P3): Rust's `regex` crate matches `\d` against
        // *any* Unicode digit (Arabic-Indic numerals etc.). The
        // timestamps generated by `mcp_config.rs` are always
        // ASCII, so use `[0-9]` to avoid accidental false
        // positives on non-ASCII-digit filenames.
        Regex::new(r"^[A-Za-z0-9_.\-]+\.[0-9]{8}_[0-9]{6}(-[0-9]{2})?\.bak$")
            .expect("timestamped backup regex must compile")
    })
}

#[derive(Debug, Clone, Serialize)]
pub struct QuarantinedBakFinding {
    pub path: PathBuf,
    pub current_mode: u32,
    /// First matched token-shape pattern, or `None` if the file
    /// matched the filename regex but has no token shape (still
    /// emitted as a hygiene finding when the file lives under
    /// the project tree).
    pub matched_pattern: Option<String>,
}

impl QuarantinedBakFinding {
    pub fn to_finding(&self) -> super::Finding {
        let mode_str = format!("0o{:o}", self.current_mode & 0o777);
        let title = if let Some(pat) = &self.matched_pattern {
            format!(
                "timestamped MCP config backup {} matches token-shape `{}` with mode {} (target 0o600)",
                self.path.display(),
                pat,
                mode_str,
            )
        } else {
            format!(
                "timestamped MCP config backup {} present (hygiene; mode {})",
                self.path.display(),
                mode_str,
            )
        };
        super::Finding {
            id: FM_ID,
            severity: FM_SEVERITY,
            subsystem: FM_SUBSYSTEM,
            title,
            confidence: 0.9,
            evidence: serde_json::json!({
                "path": self.path.to_string_lossy(),
                "current_mode_octal": mode_str,
                "target_mode_octal": format!("0o{:o}", SAFE_MODE),
                "matched_pattern": self.matched_pattern,
                "auto_fix_summary": format!(
                    "`am doctor fix --only fm-mcp-config-files-quarantined-bak-files-with-tokens --yes` chmods this backup to 0o{:o} via the chokepoint. Reversible via `am doctor undo <run-id>` (the prior mode is recorded in actions.jsonl). The backup file CONTENT is not moved or modified.",
                    SAFE_MODE,
                ),
                "manual_remediation": {
                    "steps": [
                        "Auto-fix (preferred): `am doctor fix --only fm-mcp-config-files-quarantined-bak-files-with-tokens --yes`. The chokepoint chmods each flagged backup to 0o600 and records the prior mode so `am doctor undo <run-id>` is byte-identical-reversible.",
                        "Manual alternative: `chmod 600 <path>` per entry — same canonical defense-in-depth mode.",
                        "If the token was already rotated and you want the backup out of the config dir entirely, move it into a private quarantine: `mkdir -p .doctor/quarantine/mcp-config-bak && chmod 700 .doctor/quarantine/mcp-config-bak && mv <path> .doctor/quarantine/mcp-config-bak/`. This is a stronger remediation than the auto-fix and remains manual.",
                    ],
                },
            }),
            remediation: FindingRemediation {
                command: super::fix_only_command(FM_ID),
                explain_command: format!("am doctor explain {FM_ID}"),
                auto_fixable: true,
                estimated_actions: 1,
            },
        }
    }
}

#[derive(Debug, Clone, Default)]
pub struct DetectInputs {
    /// Override candidate directories. Production callers leave
    /// empty; the detector enumerates via
    /// `mcp_config::detect_mcp_config_locations_default()`.
    pub dir_overrides: Option<Vec<PathBuf>>,
}

pub fn detect(inputs: &DetectInputs) -> Vec<QuarantinedBakFinding> {
    let dirs: Vec<PathBuf> = if let Some(overrides) = &inputs.dir_overrides {
        overrides.clone()
    } else {
        mcp_agent_mail_core::mcp_config::detect_mcp_config_locations_default()
            .into_iter()
            .filter_map(|loc| loc.config_path.parent().map(Path::to_path_buf))
            .collect::<std::collections::HashSet<_>>()
            .into_iter()
            .collect()
    };

    let mut out: Vec<QuarantinedBakFinding> = Vec::new();
    let regex = backup_filename_regex();
    for dir in dirs {
        let Ok(rd) = fs::read_dir(&dir) else {
            continue;
        };
        for entry in rd.flatten() {
            let path = entry.path();
            let Some(basename) = path.file_name().and_then(|s| s.to_str()) else {
                continue;
            };
            if !regex.is_match(basename) {
                continue;
            }
            let Ok(meta) = fs::symlink_metadata(&path) else {
                continue;
            };
            if !meta.file_type().is_file() {
                // Symlinks and dirs are out of scope here.
                continue;
            }
            // The "wider than owner-only" gate is a POSIX mode-bit concept.
            // On Windows there are no group/other permission bits, so this
            // FM is N/A and never fires (mirrors the `#[cfg(not(unix))]`
            // no-op pattern in `path_order_shadows_am`/`empty_or_truncated_db`).
            let Some((mode, world_or_group)) = mode_and_world_or_group(&meta) else {
                continue;
            };
            let pattern = token_pattern_in_head(&path);
            // Emit if: (a) has token-shape AND wider than owner-only, OR
            // (b) has token-shape regardless of mode (hygiene — backup
            // shouldn't be left lying around). For now we ONLY emit
            // when there's a token shape; tokenless backups are
            // operator hygiene below this FM's scope.
            if pattern.is_some() && world_or_group {
                out.push(QuarantinedBakFinding {
                    path,
                    current_mode: mode,
                    matched_pattern: pattern,
                });
            }
        }
    }
    out
}

/// `Some((mode, world_or_group))` on Unix where `mode` is the POSIX mode and
/// `world_or_group` is `mode & 0o077 != 0`. `None` on Windows, where there
/// are no group/other permission bits and the FM is inapplicable.
#[cfg(unix)]
fn mode_and_world_or_group(meta: &std::fs::Metadata) -> Option<(u32, bool)> {
    use std::os::unix::fs::PermissionsExt;
    let mode = meta.permissions().mode();
    Some((mode, mode & 0o077 != 0))
}

#[cfg(not(unix))]
fn mode_and_world_or_group(_meta: &std::fs::Metadata) -> Option<(u32, bool)> {
    None
}

fn token_pattern_in_head(path: &Path) -> Option<String> {
    use std::io::Read;
    let mut buf = Vec::with_capacity(SCAN_PREFIX_BYTES);
    let f = fs::File::open(path).ok()?;
    let mut take = f.take(SCAN_PREFIX_BYTES as u64);
    take.read_to_end(&mut buf).ok()?;
    let lowered = String::from_utf8_lossy(&buf).to_lowercase();
    for pat in TOKEN_SHAPE_PATTERNS {
        if lowered.contains(&pat.to_lowercase()) {
            return Some((*pat).to_string());
        }
    }
    None
}

/// Fixer. Routes through `mutate()` with `Op::Chmod { mode: SAFE_MODE }`.
///
/// One finding represents one file (the detector emits one per
/// matched backup). If the file has vanished between detect-time
/// and fix-time, count as `actions_skipped` and return Ok. The
/// chokepoint already refuses symlinks (the detector pre-filters
/// them out as well) and opens the chmod target via O_NOFOLLOW,
/// so a symlink-swap attack between detect and fix cannot redirect
/// the chmod to an out-of-scope file.
pub fn fix(
    ctx: &MutateContext,
    finding: &QuarantinedBakFinding,
) -> Result<FixOutcome, MutateError> {
    if !finding.path.exists() {
        return Ok(FixOutcome {
            actions_taken: 0,
            actions_skipped: 1,
            quarantined_paths: Vec::new(),
        });
    }
    mutate(ctx, &finding.path, Op::Chmod { mode: SAFE_MODE })?;
    Ok(FixOutcome {
        actions_taken: 1,
        actions_skipped: 0,
        quarantined_paths: Vec::new(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    // Production code no longer imports PermissionsExt at module scope
    // (Windows has no POSIX modes); the tests exercise Unix mode semantics
    // and only run on the host, so the import lives here.
    use std::os::unix::fs::PermissionsExt;
    use tempfile::TempDir;

    fn write_with_mode(path: &Path, content: &str, mode: u32) {
        fs::write(path, content).unwrap();
        fs::set_permissions(path, fs::Permissions::from_mode(mode)).unwrap();
    }

    /// **NEGATIVE TEST FIRST** (pass-35V lesson): empty config
    /// dir → no finding.
    #[test]
    fn detector_skips_empty_dir() {
        let td = TempDir::new().unwrap();
        let inputs = DetectInputs {
            dir_overrides: Some(vec![td.path().to_path_buf()]),
        };
        let findings = detect(&inputs);
        assert!(findings.is_empty());
    }

    /// **NEGATIVE TEST**: timestamped backup but with no
    /// token-shape content → no finding.
    #[test]
    fn detector_skips_backup_without_token_shape() {
        let td = TempDir::new().unwrap();
        let f = td.path().join("config.json.20260101_120000.bak");
        write_with_mode(&f, r#"{"foo":"bar"}"#, 0o644);
        let inputs = DetectInputs {
            dir_overrides: Some(vec![td.path().to_path_buf()]),
        };
        let findings = detect(&inputs);
        assert!(findings.is_empty());
    }

    /// **NEGATIVE TEST**: token-shape but already 0o600 (owner
    /// only) → no finding.
    #[test]
    fn detector_skips_already_owner_only_mode() {
        let td = TempDir::new().unwrap();
        let f = td.path().join("config.json.20260101_120000.bak");
        write_with_mode(&f, r#"{"authorization":"Bearer x"}"#, 0o600);
        let inputs = DetectInputs {
            dir_overrides: Some(vec![td.path().to_path_buf()]),
        };
        let findings = detect(&inputs);
        assert!(findings.is_empty());
    }

    /// **NEGATIVE TEST**: filename matches `.bak` suffix but
    /// NOT the timestamped pattern (handled by the suffix-based
    /// `world_readable_token_bak` FM instead) → no finding.
    #[test]
    fn detector_skips_non_timestamped_bak() {
        let td = TempDir::new().unwrap();
        let f = td.path().join("config.json.bak");
        write_with_mode(&f, r#"{"authorization":"Bearer x"}"#, 0o644);
        let inputs = DetectInputs {
            dir_overrides: Some(vec![td.path().to_path_buf()]),
        };
        let findings = detect(&inputs);
        assert!(
            findings.is_empty(),
            "non-timestamped .bak is out of scope here"
        );
    }

    #[test]
    fn detector_flags_timestamped_world_readable_backup_with_token() {
        let td = TempDir::new().unwrap();
        let f = td.path().join("config.json.20260101_120000.bak");
        write_with_mode(&f, r#"{"authorization":"Bearer abc"}"#, 0o644);
        let inputs = DetectInputs {
            dir_overrides: Some(vec![td.path().to_path_buf()]),
        };
        let findings = detect(&inputs);
        assert_eq!(findings.len(), 1);
        assert_eq!(findings[0].path, f);
        assert_eq!(findings[0].current_mode & 0o777, 0o644);
        assert!(findings[0].matched_pattern.is_some());
    }

    #[test]
    fn detector_flags_timestamped_with_suffix_index_token() {
        let td = TempDir::new().unwrap();
        let f = td.path().join("config.json.20260101_120000-02.bak");
        write_with_mode(&f, "HTTP_BEARER_TOKEN=secret\n", 0o644);
        let inputs = DetectInputs {
            dir_overrides: Some(vec![td.path().to_path_buf()]),
        };
        let findings = detect(&inputs);
        assert_eq!(findings.len(), 1);
        assert_eq!(findings[0].path, f);
    }

    #[test]
    fn detector_skips_symlinks() {
        let td = TempDir::new().unwrap();
        let real = td.path().join("config.json.20260101_120000.bak");
        write_with_mode(&real, r#"{"token":"x"}"#, 0o644);
        let link = td.path().join("link.20260101_120000.bak");
        std::os::unix::fs::symlink(&real, &link).unwrap();
        // detect() walks every file in the dir — the real file
        // will be found. We just want to confirm the symlink
        // ITSELF is rejected via symlink_metadata + is_file()
        // check.
        let inputs = DetectInputs {
            dir_overrides: Some(vec![td.path().to_path_buf()]),
        };
        let findings = detect(&inputs);
        // The real file matches the regex and has token shape,
        // so it WILL be flagged. The symlink should NOT be in
        // the findings list.
        let paths: Vec<_> = findings.iter().map(|f| f.path.clone()).collect();
        assert!(paths.contains(&real));
        assert!(!paths.contains(&link), "symlinks must not be flagged");
    }

    #[test]
    fn finding_serializes_with_pattern_and_mode() {
        let f = QuarantinedBakFinding {
            path: "/x/config.json.20260101_120000.bak".into(),
            current_mode: 0o100644,
            matched_pattern: Some("\"authorization\"".to_string()),
        };
        let g = f.to_finding();
        let s = serde_json::to_string(&g).unwrap();
        assert!(s.contains(FM_ID));
        assert!(s.contains("\"current_mode_octal\":\"0o644\""));
        // The matched_pattern value contains literal quote chars,
        // which serde_json escapes to `\"` in the output. We
        // assert on the unquoted `authorization` substring to
        // stay agnostic about the JSON encoding shape.
        assert!(s.contains("authorization"));
        assert!(s.contains("auto_fix_summary"));
        assert!(s.contains("\"auto_fixable\":true"));
        assert!(s.contains("\"estimated_actions\":1"));
        assert!(s.contains("\"target_mode_octal\":\"0o600\""));
    }

    #[test]
    fn regex_accepts_canonical_patterns() {
        let re = backup_filename_regex();
        assert!(re.is_match("config.json.20260101_120000.bak"));
        assert!(re.is_match("settings.json.20251231_235959.bak"));
        assert!(re.is_match("mcp.json.20260101_120000-01.bak"));
        assert!(re.is_match("mcp.json.20260101_120000-99.bak"));
    }

    #[test]
    fn regex_rejects_unrelated_patterns() {
        let re = backup_filename_regex();
        assert!(!re.is_match("config.json.bak")); // no timestamp
        assert!(!re.is_match("config.json.2026.bak")); // partial date
        assert!(!re.is_match("config.json.20260101.bak")); // no time
        assert!(!re.is_match("config.json.20260101_120000")); // no .bak
        assert!(!re.is_match("config.json.20260101_120000-1.bak")); // single digit suffix
        assert!(!re.is_match("config.20260101_120000.bak.txt")); // trailing suffix
    }

    /// pass-35AA review F3 (Gemini P3): the ASCII-only `[0-9]`
    /// digit class must NOT match Unicode digits like
    /// Arabic-Indic numerals (٠١٢٣٤٥٦٧٨٩). The previous
    /// `\d{8}` form would have false-positive on these.
    #[test]
    fn regex_rejects_unicode_digits() {
        let re = backup_filename_regex();
        // Arabic-Indic digits — equivalent to "20260101_120000".
        // Rust's `\d` matches these by default; ASCII `[0-9]`
        // does not.
        assert!(!re.is_match("config.json.٢٠٢٦٠١٠١_١٢٠٠٠٠.bak"));
        // Mixed ASCII + Unicode digits.
        assert!(!re.is_match("config.json.2026٠١٠١_120000.bak"));
    }

    fn ctx_for(td: &TempDir, run_id: &str) -> MutateContext {
        let run_dir = crate::doctor::runs::scaffold_run_dir(td.path(), run_id).unwrap();
        let actions = fs::OpenOptions::new()
            .create(true)
            .append(true)
            .open(run_dir.join("actions.jsonl"))
            .unwrap();
        MutateContext {
            run_id: run_id.into(),
            run_dir,
            capabilities: crate::doctor::mutate::Capabilities {
                write_scopes: vec![td.path().to_path_buf()],
            },
            actions_file: std::sync::Mutex::new(actions),
            fixer_id: FM_ID.into(),
            repo_root: td.path().to_path_buf(),
            dry_run: false,
            start: std::time::Instant::now(),
            extra_locks: Vec::new(),
        }
    }

    /// **NEGATIVE TEST FIRST**: a vanished path (the file was
    /// rotated between detect and fix) counts as
    /// `actions_skipped` and never errors.
    #[test]
    fn fixer_skips_vanished_path() {
        let td = TempDir::new().unwrap();
        let ctx = ctx_for(&td, "2026-05-16T00-00-00Z__qbak_vanished");
        let finding = QuarantinedBakFinding {
            path: td.path().join("ghost.20260101_120000.bak"),
            current_mode: 0o100644,
            matched_pattern: Some("token=".to_string()),
        };
        let outcome = fix(&ctx, &finding).expect("fix");
        assert_eq!(outcome.actions_taken, 0);
        assert_eq!(outcome.actions_skipped, 1);
    }

    #[test]
    fn fixer_chmods_world_readable_backup_to_0o600() {
        let td = TempDir::new().unwrap();
        let f = td.path().join("config.json.20260101_120000.bak");
        write_with_mode(&f, r#"{"authorization":"Bearer abc"}"#, 0o644);

        let ctx = ctx_for(&td, "2026-05-16T00-00-00Z__qbak_chmod");
        let finding = QuarantinedBakFinding {
            path: f.clone(),
            current_mode: 0o100644,
            matched_pattern: Some("\"authorization\"".to_string()),
        };
        let outcome = fix(&ctx, &finding).expect("fix");
        assert_eq!(outcome.actions_taken, 1);
        assert_eq!(outcome.actions_skipped, 0);

        let mode = fs::metadata(&f).unwrap().permissions().mode() & 0o7777;
        assert_eq!(
            mode, 0o600,
            "post-fix mode must be exactly 0o600 (defense-in-depth)"
        );

        // Sanity: the file CONTENT is untouched.
        let content = fs::read_to_string(&f).unwrap();
        assert_eq!(content, r#"{"authorization":"Bearer abc"}"#);
    }

    /// Idempotence: re-running on an already-0o600 file is a no-op
    /// (mutate returns Ok; mode is unchanged). The detector wouldn't
    /// enqueue a 0o600 entry, but the fixer must tolerate it if a
    /// caller hand-builds the finding.
    #[test]
    fn fixer_is_idempotent_on_already_safe_mode() {
        let td = TempDir::new().unwrap();
        let f = td.path().join("config.json.20260101_120000.bak");
        write_with_mode(&f, "HTTP_BEARER_TOKEN=keep-me", 0o600);

        let ctx = ctx_for(&td, "2026-05-16T00-00-00Z__qbak_idem");
        let finding = QuarantinedBakFinding {
            path: f.clone(),
            current_mode: 0o100600,
            matched_pattern: Some("HTTP_BEARER_TOKEN".to_string()),
        };
        let outcome = fix(&ctx, &finding).expect("fix");
        assert_eq!(outcome.actions_taken, 1);
        let mode = fs::metadata(&f).unwrap().permissions().mode() & 0o7777;
        assert_eq!(mode, 0o600);
    }
}
